#include "hash_tables.h"
/**
  *key_index - generates the index at which to store the key
  *@key: the key generated by the hash function
  *@size: the size of the table
  *
  *Return: the index to store the data
  */
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	return (hash_djb2(key) & (size - 1));
}
